[workspace]
authors = ["Rabeez Riaz <ruoter123@gmail.com>"]
channels = ["conda-forge"]
name = "sumran_ecommerce_scaper"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
nvim = "nvim"
catalog = "python catalog.py"
items = "python items.py"
process = "python process.py"

[dependencies]
python = "3.12.*"
httpx = ">=0.28.1,<0.29"
selectolax = ">=0.3.29,<0.4"
polars = ">=1.29.0,<2"
tqdm = ">=4.67.1,<5"
ipykernel = ">=6.29.5,<7"
pip = ">=25.1.1,<26"
python-dotenv = ">=1.1.0,<2"
